version: "3"
services:
  web:
    build:
      context: ./cmd/web
      dockerfile: ../../images/client/Dockerfile
    ports:
      - "12345:80"
    volumes:
      - ./cmd/web:/ihaq-client
    links:
      - redis
    command: -i localhost:8080
  api:
    build: images/publisher
    ports:
      - "8080:8080"
    links:
      - redis
    command: --redis-server-name=redis
  worker:
    build: images/worker
    links:
      - redis
    command: --redis-server-name=redis
  redis:
    image: redis
