name: CI

on: [pull_request]

jobs:
  build:
    name: Building ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['client','worker','publisher']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go	
      uses: actions/setup-go@v1	
      with:	
        go-version: 1.13
    - name: Build image
      run: |
        make build-${{ matrix.image }}-binaries
